apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-task-list-devops
  namespace: task-list-devops
spec: 
  rules:
    - host: task-list-devops.<IP>.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-task-list-devops
                port: 
                  number: 80
                  
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-task-list-devops
                port: 
                  number: 8080